# Updated auth-gateway Argo CD Application with Istio sidecar injection
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after Istio is ready
spec:
  project: default
  sources:
    # Private config repo for sensitive values
    - repoURL: https://github.com/mr26/private-config.git
      targetRevision: main
      ref: values
    # Main repo with Helm chart
    - repoURL: https://github.com/mr26/notes-auth-service.git
      targetRevision: main
      path: auth-gateway/helm
      helm:
        valueFiles:
          - $values/auth-gateway/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled

