apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: mehdi-sample-bucket-123
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-east-1
    objectOwnership: BucketOwnerEnforced
    paymentConfiguration:
      payer: BucketOwner
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: aws-provider-config