apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: apidb-composition
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: ApiDB
  resources:
    # Step 1: Create a new RDS instance
    - name: api-rds-db
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: Instance
        metadata:
          name: rds-api-db
        spec:
          forProvider:
            identifier: rds-api-db
            instanceClass: db.t3.micro
            region: us-east-1
            engine: mysql
            engineVersion: "8.0"
            allocatedStorage: 20
            autoGeneratePassword: true
            skipFinalSnapshot: true
            username: adminuser
          writeConnectionSecretToRef:
            name: connection-details
            namespace: placeholder-namespace
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-provider-config
          patches:
            - fromFieldPath: "spec.targetNamespace"
              toFieldPath: "spec.writeConnectionSecretToRef.namespace"