apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: apidb-composition
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: ApiDB
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
            base:
              apiVersion: database.aws.crossplane.io/v1beta1
              kind: RDSInstance
              metadata:
                name: rds-api-db
              spec:
                forProvider:
                  region: us-east-1
                  engine: mysql
                  engineVersion: "8.0"
                  dbInstanceClass: db.t3.micro
                  allocatedStorage: 20
                  publiclyAccessible: false
                  skipFinalSnapshot: true
                writeConnectionSecretToRef:
                  name: connection-details
                  namespace: placeholder-namespace
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: "spec.targetNamespace"
                toFieldPath: "spec.writeConnectionSecretToRef.namespace"
              - fromFieldPath: "spec.targetNamespace"
                toFieldPath: "metadata.namespace"