apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apidbs.platform.example.org
spec:
  group: platform.example.org
  names:
    kind: ApiDB
    plural: apidbs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  type: string
                  description: "Namespace where K8s secret will be stored"
