apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apidbs.platform.example.org
spec:
  scope: Cluster
  group: platform.example.org
  names:
    kind: ApiDB
    plural: apidbs
  claimNames:
    kind: ApiDBClaim
    plural: apidbclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            parameters:
              type: object
              properties:
                dbName:
                  type: string
              required:
                - dbName
