apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  namespace: atlantis
  labels:
    app.kubernetes.io/name: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atlantis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atlantis
    spec:
      containers:
      - name: atlantis
        image: ghcr.io/runatlantis/atlantis:latest
        env:
        # Org Allowlist
        - name: ATLANTIS_REPO_ALLOWLIST
          value: "github.com/mr26/*"
        - name: ATLANTIS_PORT
          value: "4141"

        # GitHub Config
        - name: ATLANTIS_GH_USER
          value: "mr26"
        - name: ATLANTIS_GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: token
        - name: ATLANTIS_GH_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: atlantis-github
              key: webhookSecret
        - name: MY_PUBLIC_IP
          valueFrom:
            secretKeyRef:
              name: my-public-ip-secret
              key: ip
        - name: TF_VAR_my_public_ip
          value: "$(MY_PUBLIC_IP)"
        ports:
        - name: atlantis
          containerPort: 4141
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 2Gi
            cpu: 1
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthz
            port: 4141
            scheme: HTTP
        readinessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthz
            port: 4141
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  type: LoadBalancer
  ports:
    - name: atlantis
      port: 80
      targetPort: 4141
  selector:
    app.kubernetes.io/name: atlantis