apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: atlantis
spec:
  project: default

  source:
    repoURL: https://github.com/mr26/platform-sre-devops-lab.git
    path: charts/atlantis
    chart: atlantis
    targetRevision: 4.21.0
    helm:
      releaseName: atlantis
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis

  syncPolicy:
    automated:
      selfHeal: true
      prune: true