apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.108.0
    chart: opentelemetry-collector
    helm:
      values: |
        mode: deployment
        
        image:
          repository: otel/opentelemetry-collector-contrib
        
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          
          processors:
            batch:
              timeout: 1s
              send_batch_size: 1024
          
          exporters:
            otlp/tempo:
              endpoint: tempo.observability.svc.cluster.local:4317
              tls:
                insecure: true
          
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/tempo]
        
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
