apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mtls-policy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after istiod (wave 1)
spec:
  project: default
  source:
    repoURL: https://github.com/mr26/platform-sre-devops-lab.git
    path: mgmt-apps/cluster-infra/istio/policies
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

